protomask_cub200_sam2_params = {
    "model": "protomask",
    "batch_size": 16,
    "num_masks": 11,
    "init_feature_weights": True,
    "warm_optimizer_lr": 0.001,
    "joint_optimizer_lr.backbone": 6e-05,
    "joint_optimizer_lr.prototype_vectors": 0.003,
    "fine_tune_optimizer_lr": 0.0003,
    "joint_scheduler.gamma": 0.5,
    "joint_scheduler.step_size": 35,
    "joint_epochs": 100,
    "warmup_epochs": 0,
    "fine_tune_epochs": 10,
    "coefs.crs_ent": 1,
    "coefs.clst": 0.8,
    "coefs.sep": 0.2,
    "coefs.div": 0.2,
    "coefs.l1": 0.001,
    "prototypes_per_class": 10,
    "prototype_channel_num": 1280,
    "accumulate_batches": 4,
    "features": "resnet50",
    "crop_input": True,
    "segmentation_method": "sam2",
    "fill_background_method": "original",
    "min_bbox_size": 0.0,
    "augmentation_pipeline": [["protomask", "medium"], ["photometric", "medium"]],
}

protomask_cub200_slit_params = {
    "model": "protomask",
    "batch_size": 16,
    "num_masks": 8,
    "init_feature_weights": True,
    "warm_optimizer_lr": 0.001,
    "joint_optimizer_lr.backbone": 9.4e-05,
    "joint_optimizer_lr.prototype_vectors": 0.0027,
    "fine_tune_optimizer_lr": 0.0003,
    "joint_scheduler.gamma": 0.5,
    "joint_scheduler.step_size": 35,
    "joint_epochs": 100,
    "warmup_epochs": 0,
    "fine_tune_epochs": 10,
    "coefs.crs_ent": 1,
    "coefs.clst": 0.8,
    "coefs.sep": 0.2,
    "coefs.div": 0.2,
    "coefs.l1": 0.001,
    "prototypes_per_class": 10,
    "prototype_channel_num": 1280,
    "accumulate_batches": 4,
    "features": "resnet50",
    "crop_input": True,
    "segmentation_method": "slit",
    "fill_background_method": "original",
    "min_bbox_size": 0.0,
    "augmentation_pipeline": [["protomask", "medium"], ["photometric", "medium"]],
}

protomask_dogs_sam2_params = {
    "model": "protomask",
    "batch_size": 16,
    "num_masks": 13,
    "init_feature_weights": True,
    "warm_optimizer_lr": 0.001,
    "joint_optimizer_lr.backbone": 1e-05,
    "joint_optimizer_lr.prototype_vectors": 0.003,
    "fine_tune_optimizer_lr": 0.0003,
    "joint_scheduler.gamma": 0.5,
    "joint_scheduler.step_size": 30,
    "joint_epochs": 100,
    "warmup_epochs": 0,
    "fine_tune_epochs": 10,
    "coefs.crs_ent": 1,
    "coefs.clst": 0.8,
    "coefs.sep": 0.2,
    "coefs.div": 0.2,
    "coefs.l1": 0.001,
    "prototypes_per_class": 10,
    "prototype_channel_num": 1280,
    "accumulate_batches": 4,
    "features": "resnet50",
    "crop_input": True,
    "segmentation_method": "sam2",
    "fill_background_method": "original",
    "min_bbox_size": 0.0,
    "augmentation_pipeline": [["protomask", "medium"], ["photometric", "medium"]],
}

protomask_dogs_slit_params = {
    "model": "protomask",
    "batch_size": 16,
    "num_masks": 10,
    "init_feature_weights": True,
    "warm_optimizer_lr": 0.001,
    "joint_optimizer_lr.backbone": 2.9e-05,
    "joint_optimizer_lr.prototype_vectors": 0.003,
    "fine_tune_optimizer_lr": 0.0003,
    "joint_scheduler.gamma": 0.5,
    "joint_scheduler.step_size": 30,
    "joint_epochs": 100,
    "warmup_epochs": 0,
    "fine_tune_epochs": 10,
    "coefs.crs_ent": 1,
    "coefs.clst": 0.8,
    "coefs.sep": 0.2,
    "coefs.div": 0.2,
    "coefs.l1": 0.001,
    "prototypes_per_class": 10,
    "prototype_channel_num": 1280,
    "accumulate_batches": 4,
    "features": "resnet50",
    "crop_input": True,
    "segmentation_method": "slit",
    "fill_background_method": "original",
    "min_bbox_size": 0.0,
    "augmentation_pipeline": [["protomask", "medium"], ["photometric", "medium"]],
}

protomask_cars196_sam2_params = {
    "model": "protomask",
    "batch_size": 16,
    "num_masks": 16,
    "init_feature_weights": True,
    "warm_optimizer_lr": 0.001,
    "joint_optimizer_lr.backbone": 6e-05,
    "joint_optimizer_lr.prototype_vectors": 0.002,
    "fine_tune_optimizer_lr": 0.0003,
    "joint_scheduler.gamma": 0.5,
    "joint_scheduler.step_size": 35,
    "joint_epochs": 100,
    "warmup_epochs": 0,
    "fine_tune_epochs": 10,
    "coefs.crs_ent": 1,
    "coefs.clst": 0.8,
    "coefs.sep": 0.2,
    "coefs.div": 0.2,
    "coefs.l1": 0.001,
    "prototypes_per_class": 10,
    "prototype_channel_num": 1280,
    "accumulate_batches": 4,
    "features": "resnet50",
    "crop_input": True,
    "segmentation_method": "sam2",
    "fill_background_method": "original",
    "min_bbox_size": 0.0,
    "augmentation_pipeline": [["protomask", "medium"], ["photometric", "medium"]],
}

protomask_cars196_slit_params = {
    "model": "protomask",
    "batch_size": 16,
    "num_masks": 11,
    "init_feature_weights": True,
    "warm_optimizer_lr": 0.001,
    "joint_optimizer_lr.backbone": 7.3e-05,
    "joint_optimizer_lr.prototype_vectors": 0.0035,
    "fine_tune_optimizer_lr": 0.0003,
    "joint_scheduler.gamma": 0.5,
    "joint_scheduler.step_size": 35,
    "joint_epochs": 100,
    "warmup_epochs": 0,
    "fine_tune_epochs": 10,
    "coefs.crs_ent": 1,
    "coefs.clst": 0.8,
    "coefs.sep": 0.2,
    "coefs.div": 0.2,
    "coefs.l1": 0.001,
    "prototypes_per_class": 10,
    "prototype_channel_num": 1280,
    "accumulate_batches": 4,
    "features": "resnet50",
    "crop_input": True,
    "segmentation_method": "slit",
    "fill_background_method": "original",
    "min_bbox_size": 0.0,
    "augmentation_pipeline": [["protomask", "medium"], ["photometric", "medium"]],
}
