# With input bb cropping + resnet50
protopool_cub200_params = {
    "model": "protopool",
    "batch_size": 64,
    "init_feature_weights": True,
    "warm_optimizer_lr": 2e-3,
    "joint_optimizer_lr.backbone": 7.9e-05,
    "joint_optimizer_lr.add_on_layers": 1.3e-4,
    "joint_optimizer_lr.prototype_vectors": 9e-4,
    "fine_tune_optimizer_lr": 5e-4,
    "joint_scheduler.gamma": 0.5,
    "joint_scheduler.step_size": 20,
    "coefs.crs_ent": 1,
    "coefs.clst": 0.8,
    "coefs.sep": 0.08,
    "coefs.orth": 1.0,
    "coefs.l1": 0.001,
    "coefs.tau_start": 1.0,
    "coefs.tau_end": 0.001,
    "coefs.decreasing_interval": 50,
    "joint_epochs": 100,
    "warmup_epochs": 25,
    "fine_tune_epochs": 10,
    "num_prototypes": 205,
    "descriptives": 10,
    "prototype_shape": [128, 1, 1],
    "augmentation_pipeline": [["geometric", "medium"], ["photometric", "medium"]],
}

protopool_cars196_params = {
    "model": "protopool",
    "batch_size": 64,
    "init_feature_weights": True,
    "warm_optimizer_lr": 1e-3,
    "joint_optimizer_lr.backbone": 1.8e-4,
    "joint_optimizer_lr.add_on_layers": 8e-4,
    "joint_optimizer_lr.prototype_vectors": 4.5e-4,
    "fine_tune_optimizer_lr": 1.7e-4,
    "joint_scheduler.gamma": 0.5,
    "joint_scheduler.step_size": 35,
    "coefs.crs_ent": 1,
    "coefs.clst": 0.8,
    "coefs.sep": 0.08,
    "coefs.orth": 1.0,
    "coefs.l1": 0.001,
    "coefs.tau_start": 1.0,
    "coefs.tau_end": 0.001,
    "coefs.decreasing_interval": 50,
    "joint_epochs": 100,
    "warmup_epochs": 30,
    "fine_tune_epochs": 10,
    "num_prototypes": 201,
    "descriptives": 10,
    "prototype_shape": [128, 1, 1],
    "augmentation_pipeline": [["geometric", "medium"], ["photometric", "medium"]],
}

protopool_nico_params = {
    "model": "protopool",
    "batch_size": 64,
    "init_feature_weights": True,
    "warm_optimizer_lr": 2.5e-3,
    "joint_optimizer_lr.backbone": 5e-05,
    "joint_optimizer_lr.add_on_layers": 3.9e-4,
    "joint_optimizer_lr.prototype_vectors": 2.9e-3,
    "fine_tune_optimizer_lr": 1e-05,
    "joint_scheduler.gamma": 0.5,
    "joint_scheduler.step_size": 30,
    "coefs.crs_ent": 1,
    "coefs.clst": 0.8,
    "coefs.sep": 0.08,
    "coefs.orth": 1.0,
    "coefs.l1": 0.001,
    "coefs.tau_start": 1.0,
    "coefs.tau_end": 0.001,
    "coefs.decreasing_interval": 10,
    "joint_epochs": 100,
    "warmup_epochs": 10,
    "fine_tune_epochs": 10,
    "num_prototypes": 50,
    "descriptives": 5,
    "prototype_shape": [128, 1, 1],
    "augmentation_pipeline": [["geometric", "medium"], ["photometric", "medium"]],
}


protopool_awa2_params = {
    "model": "protopool",
    "batch_size": 64,
    "init_feature_weights": True,
    "warm_optimizer_lr": 1.7e-3,
    "joint_optimizer_lr.backbone": 4e-05,
    "joint_optimizer_lr.add_on_layers": 2.3e-3,
    "joint_optimizer_lr.prototype_vectors": 2.6e-3,
    "fine_tune_optimizer_lr": 2.3e-05,
    "joint_scheduler.gamma": 0.5,
    "joint_scheduler.step_size": 35,
    "coefs.crs_ent": 1,
    "coefs.clst": 0.8,
    "coefs.sep": 0.08,
    "coefs.orth": 1.0,
    "coefs.l1": 0.001,
    "coefs.tau_start": 1.0,
    "coefs.tau_end": 0.001,
    "coefs.decreasing_interval": 20,
    "joint_epochs": 100,
    "warmup_epochs": 30,
    "fine_tune_epochs": 10,
    "num_prototypes": 168,
    "descriptives": 10,
    "prototype_shape": [128, 1, 1],
    "augmentation_pipeline": [["geometric", "medium"], ["photometric", "medium"]],
}
