# With input bb cropping + resnet50
protopnet_cub200_params = {
    "model": "protopnet",
    "batch_size": 64,
    "init_feature_weights": True,
    "warm_optimizer_lr": 2.7e-05,
    "joint_optimizer_lr.backbone": 4.7e-05,
    "joint_optimizer_lr.add_on_layers": 4.9e-05,
    "joint_optimizer_lr.prototype_vectors": 2.3e-3,
    "fine_tune_optimizer_lr": 1e-4,
    "joint_scheduler.gamma": 0.5,
    "joint_scheduler.step_size": 35,
    "joint_epochs": 100,
    "warmup_epochs": 5,
    "fine_tune_epochs": 10,
    "coefs.crs_ent": 1,
    "coefs.clst": 0.8,
    "coefs.sep": 0.08,
    "coefs.l1": 0.001,
    "prototypes_per_class": 10,
    "prototype_shape": [128, 1, 1],
    "augmentation_pipeline": [["geometric", "medium"], ["photometric", "medium"]],
}

protopnet_cars196_params = {
    "model": "protopnet",
    "batch_size": 64,
    "init_feature_weights": True,
    "warm_optimizer_lr": 2.5e-05,
    "joint_optimizer_lr.backbone": 1e-4,
    "joint_optimizer_lr.add_on_layers": 4.7e-4,
    "joint_optimizer_lr.prototype_vectors": 2.9e-3,
    "fine_tune_optimizer_lr": 2e-4,
    "joint_scheduler.gamma": 0.5,
    "joint_scheduler.step_size": 30,
    "joint_epochs": 100,
    "warmup_epochs": 10,
    "fine_tune_epochs": 10,
    "coefs.crs_ent": 1,
    "coefs.clst": 0.8,
    "coefs.sep": 0.08,
    "coefs.l1": 0.001,
    "prototypes_per_class": 10,
    "prototype_shape": [128, 1, 1],
    "augmentation_pipeline": [["geometric", "medium"], ["photometric", "medium"]],
}

protopnet_nico_params = {
    "model": "protopnet",
    "batch_size": 64,
    "init_feature_weights": True,
    "warm_optimizer_lr": 4e-4,
    "joint_optimizer_lr.backbone": 3.9e-05,
    "joint_optimizer_lr.add_on_layers": 1.2e-05,
    "joint_optimizer_lr.prototype_vectors": 3.8e-4,
    "fine_tune_optimizer_lr": 1.7e-3,
    "joint_scheduler.gamma": 0.5,
    "joint_scheduler.step_size": 35,
    "joint_epochs": 100,
    "warmup_epochs": 10,
    "fine_tune_epochs": 10,
    "coefs.crs_ent": 1,
    "coefs.clst": 0.8,
    "coefs.sep": 0.08,
    "coefs.l1": 0.001,
    "prototypes_per_class": 5,
    "prototype_shape": [128, 1, 1],
    "augmentation_pipeline": [["geometric", "medium"], ["photometric", "medium"]],
}

protopnet_awa2_params = {
    "model": "protopnet",
    "batch_size": 64,
    "init_feature_weights": True,
    "warm_optimizer_lr": 5.6e-05,
    "joint_optimizer_lr.backbone": 3e-05,
    "joint_optimizer_lr.add_on_layers": 2.6e-4,
    "joint_optimizer_lr.prototype_vectors": 3.7e-05,
    "fine_tune_optimizer_lr": 0.001,
    "joint_scheduler.gamma": 0.5,
    "joint_scheduler.step_size": 25,
    "joint_epochs": 75,
    "warmup_epochs": 5,
    "fine_tune_epochs": 20,
    "coefs.crs_ent": 1,
    "coefs.clst": 0.8,
    "coefs.sep": 0.08,
    "coefs.l1": 0.001,
    "prototypes_per_class": 10,
    "prototype_shape": [128, 1, 1],
    "augmentation_pipeline": [["geometric", "medium"], ["photometric", "medium"]],
}
